wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668873209
    t:
      1:
      - 55
      4: 3.9.13
      5: 0.12.18
      8:
      - 1
      - 4
      - 5
