wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668873281
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.9.13
      5: 0.12.18
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 30
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: /Users/adrielamoguis/THESIS/Demarcation-based System/Road-Lane-Detection-With-YOLOv7/models/segment/yolov7-seg.yaml
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: data/road_lanes.yaml
device:
  desc: null
  value: ''
epochs:
  desc: null
  value: 30
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.3
    cls_pw: 1.0
    copy_paste: 0.1
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.1
    mixup: 0.1
    momentum: 0.937
    mosaic: 1.0
    obj: 0.7
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.9
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
mask_ratio:
  desc: null
  value: 4
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: road-lane-seg
no_overlap:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train-seg
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train-seg/road-lane-seg
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
weights:
  desc: null
  value: ''
workers:
  desc: null
  value: 8
